Repository S2-P3-T5/Julge, pull requests merged in 2024-01, with the labels that each got.

#10 유저: 회원가입 폼에 유효한 값을 입력했을 때
  .eslintrc.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/apis/schema.ts
  src/apis/user/index.ts
  src/apis/user/schema.ts
  src/components/signup/SignupForm.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/radio-group.tsx
  src/hooks/useSignupForm.ts
  src/pages/signup/index.tsx
  src/queries/user.ts
  src/routes.ts
  src/types/form.ts
  src/types/user.ts
  tsconfig.json
Labels: 기능 추가, 유저

#19 사장님: 공고 등록 페이지 - 모바일 사이즈 UI 구현
  package-lock.json
  package.json
  src/components/NoticeRegister/noticeRegisterInput.tsx
  src/components/NoticeRegister/noticeRegisterLabel.tsx
  src/pages/notice/register/index.tsx
  tailwind.config.ts
Labels: 사장님, 디자인

#25 사장님: ( 내 가게 ) 가게정보가 없을 시 등록 버튼 구현
  src/components/shop/EmptyShopCard.tsx
  src/pages/shop/[id].tsx
Labels: 사장님, 기능 추가

#26 사장님: ( 가게 정보 등록 ) Form 및 input 구현
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/shop/register/ShopRegisterForm.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/pages/shop/register/index.tsx
Labels: 사장님, 기능 추가

#20 사장님: '로고 버튼'을 클릭하면 공고 리스트 페이지로 이동하는 기능 구현
  pnpm-lock.yaml
  src/components/NoticeRegister/noticeRegisterInput.tsx
  src/components/NoticeRegister/noticeRegisterLabel.tsx
  src/pages/notice/register/index.tsx
Labels: 사장님, 기능 추가

#31 env: pr 템플릿 생성
  .github/pull_request_template.md
Labels: 환경

#32 유저: 회원가입 폼 유효성 검사 구현
  src/components/signup/SignupForm.tsx
  src/helpers/validation.ts
  src/hooks/useSignupForm.ts
  src/lib/constants.ts
Labels: 기능 추가, 유저

#23 사장님: 공고 등록 페이지의 '등록하기' 버튼을 눌렀을 때 모달창이 나타나는 기능 구현
  package.json
  pnpm-lock.yaml
  src/components/noticeRegister/registerModal.tsx
  src/components/ui/alert-dialog.tsx
  src/pages/notice/register/index.tsx
Labels: 사장님, 기능 추가, 디자인

#13 디자인 : 페이지네이션 UI 구현
  src/components/notices/UsePagination.tsx
  src/components/ui/pagination.tsx
Labels: 디자인

#15 디자인 : 공고리스트 상세필터 버튼 UI 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/notices/FilterModal.tsx
  src/components/notices/UseButton.tsx
Labels: 디자인

#38 회원가입: 중복된 이메일을 입력하고 가입하기를 누를 시 "이미 사용 중인 이메일입니다." 모달 창 띄우기
  package.json
  pnpm-lock.yaml
  src/apis/user/index.ts
  src/components/notices/UseComboBox.tsx
  src/components/signup/SignupForm.tsx
  src/components/signup/ValidationErrorDialog.tsx
  src/helpers/error.ts
  src/hooks/useDialog.ts
  src/pages/signup/index.tsx
  src/providers/DialogProvider.tsx
  src/queries/user.ts
Labels: 기능 추가, 유저

#40 회원가입: 페이지 네비게이션 추가
  src/pages/signup/index.tsx
  src/routes.ts
Labels: 기능 추가, 회원가입

#41 사장님: ( 가게 정보 등록 ) 등록 후 완료 모달창 구현
  package.json
  src/components/shop/register/ShopRegisterForm.tsx
  src/components/shop/register/ShopRegisterFormModal.tsx
  src/pages/shop/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가

#43 공통 디자인: 공통 input 디자인 변경
  src/components/ui/input.tsx
Labels: 공통 디자인

#44 회원가입: 회원가입 페이지 디자인 완료
  src/components/signup/CheckRadioGroupItem.tsx
  src/components/signup/SignupForm.tsx
  src/components/signup/ValidationErrorDialog.tsx
  src/components/ui/dialog.tsx
  src/pages/signup/index.tsx
Labels: 디자인, 회원가입

#47 fix: NoticeListDropDownMenu import 경로 버그 수정
  src/pages/notices.tsx
Labels: 버그 수정

#49 사장님(가게 정보 상세) /shop 경로 수정
  src/pages/shops/[userId]/index.tsx
  src/pages/shops/[userId]/register/index.tsx
Labels: 사장님

#51 사장님: (가게 정보 상세) /shops 내부 경로 수정
  src/pages/shops/[shopId]/index.tsx
  src/pages/shops/register/index.tsx
Labels: 사장님

#52 사장님 ( 공고 등록 ) - 공고 등록 페이지 '등록하기' 버튼을 누르면 공고가 등록되는 api 구성
  src/apis/shop/index.ts
  src/apis/shop/schema.ts
  src/components/noticeRegister/Modal.tsx
  src/components/noticeRegister/registerModal.tsx
  src/hooks/useNoticeRegistForm.ts
  src/pages/notice/register/index.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
  src/queries/shop.ts
  src/routes.ts
  src/types/shop.ts
Labels: 사장님, 기능 추가

#54 공고 등록 페이지 모바일 디자인 수정
  src/components/noticeRegister/Modal.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
Labels: 사장님, 디자인

#56 사장님 ( 공고 등록 ) - '확인' 버튼을 누르면 공고 상세 페이지로 이동하는 기능 구현, '등록하기'버튼 디자인 수정
  src/components/noticeRegister/Modal.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
Labels: 사장님, 기능 추가, 디자인

#64 로그인: 로그인 페이지 구현
  src/apis/auth/index.ts
  src/apis/auth/schema.ts
  src/apis/user/schema.ts
  src/components/signin/SigninForm.tsx
  src/components/signin/ValidationErrorDialog.tsx
  src/helpers/auth.ts
  src/helpers/error.ts
  src/hooks/useSigninForm.ts
  src/pages/signin/index.tsx
  src/queries/auth.ts
  src/routes.ts
  src/types/signin.ts
Labels: 인증, 기능 추가, 디자인

#66 사장님: (가게 정보 등록) Form 가게 이미지 Input 구현
  next.config.js
  src/apis/shops/index.ts
  src/components/shop/register/ShopImageCard.tsx
  src/components/shop/register/ShopRegisterForm.tsx
  src/routes.ts
Labels: 사장님, 기능 추가

#68 사장님 : (가게 정보 상세) 페이지 경로 수정으로 인한 Link 경로 수정
  src/components/shop/EmptyShopCard.tsx
  src/components/shop/register/ShopRegisterFormModal.tsx
  src/routes.ts
Labels: 사장님

#70 유저: 로그인 시 유저 객체 전역상태로 저장
  src/helpers/auth.ts
  src/pages/_app.tsx
  src/providers/UserProvider.tsx
  src/queries/auth.ts
  src/types/user.ts
Labels: 기능 추가, 유저

#73 사장님 - (공고 상세 페이지): 모바일 사이즈 디자인
  public/icons/arrow_up_bold.svg
  src/components/noticeDetail/HighHourlyWageBadge.tsx
  src/components/noticeDetail/NoticeDetailPagination.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 디자인

#78 사장님 -(공고 상세 페이지): 승인하기, 거절하기 버튼과 거절완료, 승인완료 뱃지 디자인 구현
  src/components/noticeDetail/Badge.tsx
  src/components/noticeDetail/Buttons.tsx
  src/components/ui/badge.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 디자인

#80 사장님-(공고 등록 페이지, 공고 상세 페이지): url 일부 수정, 닫기 버튼 button 타입 추가
  src/components/noticeRegister/Modal.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
  src/routes.ts
Labels: 사장님, 버그 수정

#77 사장님 : (가게 정보 상세) 가게 정보 상세 카드 구현
  next.config.js
  src/apis/shops/index.ts
  src/components/shop/ShopDataCard.tsx
  src/pages/shops/[shopId]/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가

#84 fix: routes.ts의 Api 잘못된 경로 수정
  src/apis/shop/index.ts
  src/routes.ts
Labels: 사장님, 버그 수정

#85 사장님 - (공고 등록 페이지): 공고 등록 input 필수값 유효성 검사 로직 추가, '등록하기' 눌렀을 때 리스폰스 응답을 잘 받을 때만 '등록 완료' 모달창이 나오도록 수정
  src/apis/shop/index.ts
  src/components/noticeRegister/Modal.tsx
  src/helpers/validation.ts
  src/hooks/useNoticeRegistForm.ts
  src/pages/shops/[shopId]/notices/register/index.tsx
  src/queries/shop.ts
  src/routes.ts
Labels: 사장님, 기능 추가

#89 사장님 (가게 정보 상세) 가게 공고 유무에 따른 공고 추가 / 공고 리스트 컴포넌트 구현
  src/apis/shops/index.ts
  src/components/shop/EmptyDataCard.tsx
  src/components/shop/ShopsNoticesList.tsx
  src/components/shop/ShopsNoticesListItem.tsx
  src/components/ui/ArrowUpIconCustom.tsx
  src/pages/shops/[shopId]/index.tsx
Labels: 사장님, 기능 추가

#92 공통: 에러 모달 구현
  src/apis/fetcher.ts
  src/components/common/ErrorDialog.tsx
  src/components/signin/SigninForm.tsx
  src/components/signup/SignupForm.tsx
  src/components/signup/ValidationErrorDialog.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/providers/DialogProvider.tsx
  src/providers/ErrorDialogProvider.tsx
  src/queries/auth.ts
  src/queries/user.ts
Labels: 기능 추가, 공통기능

#86 인증: 액세스 토큰 저장
  src/apis/fetcher.ts
  src/helpers/auth.ts
  src/queries/auth.ts
  tsconfig.json
Labels: 인증, 기능 추가

#95 사장님 - (공고 상세 페이지): 가게의 특정 공고 데이터들을 조회해서 공고 상세 페이지에 적용하는 기능 구현
  src/components/noticeDetail/Badge.tsx
  src/components/noticeDetail/Hooks.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가
