Repository S2-P3-T5/Julge, pull requests merged in 2024-02, with the labels that each got.

#98 공통: 새로 고침해도 로그인 유지
  package.json
  pnpm-lock.yaml
  src/apis/fetcher.ts
  src/apis/schema.ts
  src/apis/user/index.ts
  src/apis/user/schema.ts
  src/helpers/user.ts
  src/pages/signin/index.tsx
  src/providers/UserProvider.tsx
  src/queries/auth.ts
  src/queries/user.ts
Labels: 공통기능

#100 사장님 ( 가게 정보 상세) 내 가게 공고 목록 무한 스크롤 구현
  src/apis/shops/index.ts
  src/components/shop/ShopsNoticesList.tsx
  src/pages/shops/[shopId]/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가

#106 공통: 공통 레이아웃 디자인 구현
  src/components/common/EmployeeHeader.tsx
  src/components/common/EmployeeLayout.tsx
  src/components/common/EmployerHeader.tsx
  src/components/common/EmployerLayout.tsx
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/routes.ts
Labels: 디자인, 공통기능

#103 사장님 -( 공고 상세 페이지 ): 가게의 특정 공고의 지원 목록 조회 데이터를 받아와 공고 상세 페이지의 신청자 목록 페이지네이션 만들기
  package.json
  pnpm-lock.yaml
  src/components/noticeDetail/ApplicationList.tsx
  src/components/noticeDetail/NoticeDetailPagination.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가, 디자인

#107 사장님(가게 정보 상세) 가게 정보 등록 / 편집 페이지에서 X버튼 뒤로가기 기능 구현
  src/components/shop/ShopDataForm.tsx
  src/components/ui/BackPageButton.tsx
  src/routes.ts
Labels: 사장님, 기능 추가, 공통기능

#111 공통: 검색바 구현
  src/components/common/EmployeeHeader.tsx
  src/components/common/EmployeeLayout.tsx
  src/components/common/EmployerHeader.tsx
  src/components/common/EmployerLayout.tsx
  src/components/common/SearchBar.tsx
Labels: 공통기능

#112 사장님: (가게 등록/편집) - 데이터 form 필수 데이터 없을 시 제출되는 현상 수정 및 오류메시지 구현
  pnpm-lock.yaml
  src/components/shop/ShopDataForm.tsx
  src/components/shop/edit/ShopEditor.tsx
  src/components/shop/register/ShopRegister.tsx
  src/helpers/validation.ts
Labels: 사장님, 기능 추가, 버그 수정

#105 알바님(공고리스트) 리스트
  src/apis/noticeList/index.ts
  src/apis/noticeList/schema.ts
  src/components/notices/NoticeListCard.tsx
  src/components/notices/NoticeListCardList.tsx
  src/components/notices/NoticeListForm.tsx
  src/components/notices/util.ts
  src/pages/notices.tsx
  src/queries/noticeList.ts
  src/routes.ts
  src/types/noticeList.ts
Labels: 기능 추가

#115 공통: 상단 네비게이션바 메뉴를 로그인, 로그아웃 상태에 따라 변경
  src/components/common/EmployeeHeader.tsx
  src/components/common/EmployerHeader.tsx
  src/components/common/SearchBar.tsx
Labels: 공통기능

#119 사장님 -( 공고 등록 페이지 ): 시작일시 input 값을 받아 양식에 맞게 수정해서 post 할 수 있도록 수정
  src/hooks/useNoticeRegistForm.ts
  src/pages/shops/[shopId]/notices/register/index.tsx
Labels: 사장님, 기능 추가

#124 알림: 알림 박스 디자인
  src/components/common/EmployeeHeader.tsx
  src/components/common/NotificationBox.tsx
  src/components/common/NotificationCard.tsx
  src/components/ui/sheet.tsx
Labels: 공통 디자인

#129 사장님 : 가게 정보 상세 카드 컴포넌트 디자인 / 반응형 구현
  src/components/shop/ShopDataCard.tsx
Labels: 사장님, 디자인

#126 사장님 - 가게 정보 등록 / 편집 데이터 입력 form 디자인 / 반응형 구현
  src/components/shop/ShopDataForm.tsx
  src/components/shop/ShopImageCard.tsx
  src/components/ui/BackPageButton.tsx
  src/components/ui/select.tsx
Labels: 사장님, 디자인

#125 사장님 - 내 가게 / 공고 정보 없을 시 표시되는 EmptyDataCard 컴포넌트 디자인 / 반응형 구현
  src/components/shop/EmptyDataCard.tsx
Labels: 사장님, 디자인

#128 사장님 -( 공고 상세 페이지 ): MUI 패키지로 만든 페이지네이션 삭제 후 shadcn/ui 페이지네이션 컴포넌트로 수정
  package.json
  pnpm-lock.yaml
  src/components/noticeDetail/Pagination.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/routes.ts
Labels: 사장님, 기능 추가, 디자인

#135 사장님: 가게 정보 등록 / 편집 미리보기 이미지 비율 안맞는 현상 수정
  src/components/shop/ShopImageCard.tsx
Labels: 사장님, 버그 수정, 디자인

#133 사장님 :가게 정보 상세 내 공고 리스트와 리스트 아이템 디자인 / 반응형 구현
  src/components/shop/ShopsNoticesList.tsx
  src/components/shop/ShopsNoticesListItem.tsx
  src/components/ui/ArrowUpIconCustom.tsx
Labels: 사장님, 디자인

#137 refactor: 사장님 -( 공고 등록 페이지 ): 거절하기 모달 import문 추가
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 버그 수정

#139 feat:사장님 가게 상세 페이지에서 공고 선택 시 공고 상세 페이지로 이동 구현
  src/components/shop/ShopsNoticesList.tsx
Labels: 사장님, 기능 추가

#144 공통: http 에러 body의 message를 에러 메세지로 할당
  src/apis/fetcher.ts
Labels: 공통기능

#143 사장님 ( 공고 등록 ) - 공고 등록 페이지 반응형 디자인
  src/components/noticeRegister/Modal.tsx
  src/components/ui/textarea.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
Labels: 사장님, 디자인

#147 사장님 - (공고 상세 페이지): 반응형 디자인 구현
  src/components/noticeDetail/Badge.tsx
  src/components/noticeDetail/Buttons.tsx
  src/components/noticeDetail/Pagination.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 디자인

#145 사장님: /shops 기본 페이지 구현 및 접근 권한에 맞는 페이지 이동 구현
  src/apis/shop/index.ts
  src/pages/shops/index.tsx
Labels: 사장님, 기능 추가

#149 사장님 -( 공고 상세 페이지, 공고 등록 페이지): gnb 추가하기 + gnb 반응형 디자인 추가(공통디자인)
  src/components/common/EmployerHeader.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
Labels: 공통 디자인, 사장님, 공통기능

#153 사장님: (가게 정보 상세 / 등록 / 편집) 페이지 접근 권한에 맞지 않을 경우 페이지 이동 구현
  src/components/shop/ShopImageCard.tsx
  src/components/shop/edit/ShopEditor.tsx
  src/components/shop/register/ShopRegister.tsx
  src/pages/shops/[shopId]/index.tsx
  src/pages/shops/edit/[shopId].tsx
  src/pages/shops/index.tsx
  src/pages/shops/register/index.tsx
Labels: 사장님, 기능 추가

#160 공통: 공고리스트 페이지 공고데이터 받아오기 및 레이아웃 구현
  src/apis/notice/index.ts
  src/components/notices/NoticeListForm.tsx
  src/components/notices/NoticeLists.tsx
  src/components/shop/ShopsNoticesListItem.tsx
  src/pages/notices.tsx
  src/pages/notices/index.tsx
  src/queries/noticeList.ts
  src/routes.ts
Labels: 기능 추가, 디자인, 공통기능

#161 내 프로필: 마이 페이지 스켈레톤 구현
  src/components/common/EmployeeHeader.tsx
  src/pages/my/index.tsx
  src/routes.ts
Labels: 디자인

#168 배포 문제 발생 : 문법 오류 해결
  src/apis/notice/index.ts
Labels: 버그 수정

#164 공통: tailwind 동적 적용 클래스명 safelist 추가
  tailwind.config.ts
Labels: 공통 디자인, 버그 수정

#174 공통: tailwind safelist 누락 클래스 추가
  tailwind.config.ts
Labels: 문서

#166 공통: 공고리스트 - 페이지 전체공고 페이지네이션 구현
  src/apis/notice/index.ts
  src/components/notices/NoticeListPagination.tsx
  src/components/notices/NoticeLists.tsx
Labels: 기능 추가, 공통기능

#177 공통: 공고리스트 공고 클릭 시 해당 공고 지원 페이지 이동
  src/components/notices/NoticeLists.tsx
  src/routes.ts
Labels: 공통기능

#179 공통: 맞춤 공고 carousel 구현
  package.json
  pnpm-lock.yaml
  src/apis/notice/index.ts
  src/components/notices/NoticeLists.tsx
  src/components/ui/carousel.tsx
Labels: 공통기능

#181 공통: 공고리스트 - 전체 공고 정렬 구현
  src/apis/notice/index.ts
  src/components/notices/NoticeListDropDownMenu.tsx
  src/components/notices/NoticeLists.tsx
Labels: 공통기능

#183 내 프로필: 프로필 등록 폼
  src/apis/user/index.ts
  src/apis/user/schema.ts
  src/components/common/EmployeeLayout.tsx
  src/components/common/EmployerLayout.tsx
  src/components/common/ErrorDialog.tsx
  src/components/my/RegisterForm.tsx
  src/components/my/useMyRegisterForm.ts
  src/pages/my/register/index.tsx
  src/queries/user.ts
  src/types/user.ts
Labels: 기능 추가, 유저

#185 공통: 공고리스트 필터 구현
  src/apis/notice/index.ts
  src/components/notices/AddressList.tsx
  src/components/notices/AddressSelector.tsx
  src/components/notices/NoticeListDropDownMenu.tsx
  src/components/notices/NoticeListFilter.tsx
  src/components/notices/NoticeListPopover.tsx
  src/components/notices/NoticeLists.tsx
Labels: 기능 추가, 공통기능

#188 유저-( 공고 상세 페이지 ): 공고상세페이지(로그인상태)에 접근할 때 유저의 타입이 employer이면 가게 정보 상세페이지로 이동시키는 기능 구현 + employeeLayout 반응형 디자인 구현
  src/components/common/EmployeeHeader.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
Labels: 공통 디자인, 기능 추가, 유저

#196 내 프로필: 유저 프로필이 있을 때 프로필 카드 보이기
  src/components/my/ProfileCard.tsx
  src/pages/my/index.tsx
  src/queries/user.ts
Labels: 기능 추가

#195 공통: 검색시 검색 결과의 공고 표시
  src/apis/notice/index.ts
  src/components/notices/CustomNotice.tsx
  src/components/notices/NoticeLists.tsx
Labels: 공통기능

#199 알바님 - 공고 상세 페이지(로그인 상태): '신청하기' 버튼을 누르면 프로필 등록이 되어있지 않으면 alert 창이 나타나고 '확인' 버튼을 누르면 프로필 등록 페이지로 이동하는 기능 구현
  src/components/noticeDetail/Buttons.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
Labels: 알바님, 기능 추가

#200 공통: /notices 페이지 전체 디자인 및 반응형 구현
  src/components/notices/AddressList.tsx
  src/components/notices/AddressSelector.tsx
  src/components/notices/CustomNotice.tsx
  src/components/notices/NoticeListDropDownMenu.tsx
  src/components/notices/NoticeListFilter.tsx
  src/components/notices/NoticeLists.tsx
  src/components/ui/pagination.tsx
Labels: 디자인

#202 공통: 로딩창에 사용할 컴포넌트 구현
  src/components/ui/Loading.tsx
  src/styles/loading.module.css
Labels: 공통 디자인, 기능 추가

#204 내프로필: 프로필 등록 폼에 성별을 소개로 변경, 프로필 카드에 소개 추가
  src/components/my/ProfileCard.tsx
  src/components/my/RegisterForm.tsx
  src/pages/my/index.tsx
Labels: 기능 추가

#205 알바님 - 공고 상세 페이지(로그인 상태): '신청하기' 버튼을 누르면 프로필 등록이 되어있으면 신청이 완료되는 기능 구현
  src/apis/notice/index.ts
  src/apis/notice/schema.ts
  src/apis/schema.ts
  src/apis/user/schema.ts
  src/components/noticeDetail/ApplicationList.tsx
  src/helpers/auth.ts
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/routes.ts
  src/types/user.ts
Labels: 알바님, 기능 추가

#208 사장님: 가게 상세 페이지 디자인 보완 및 로고 경로 수정
  src/components/common/EmployerHeader.tsx
  src/components/notices/NoticeLists.tsx
  src/components/shop/EmptyDataCard.tsx
  src/components/shop/ShopDataForm.tsx
  src/components/shop/ShopsNoticesList.tsx
  src/components/shop/register/ShopRegister.tsx
  src/pages/shops/[shopId]/index.tsx
  src/pages/shops/edit/[shopId].tsx
  src/pages/shops/index.tsx
  src/pages/shops/register/index.tsx
Labels: 디자인

#209 사장님 - ( 공고 상세 페이지 ): 신청받은 공고를 신청자 목록에 나오도록 하고 각 신청을 승인, 거절하는 기능 구현
  src/apis/notice/index.ts
  src/apis/notice/schema.ts
  src/apis/user/schema.ts
  src/components/noticeDetail/ApplicationList.tsx
  src/components/noticeDetail/ApproveDialog.tsx
  src/components/noticeDetail/Pagination.tsx
  src/components/noticeDetail/RejectDialog.tsx
  src/components/notices/NoticeLists.tsx
  src/components/shop/ShopsNoticesList.tsx
  src/pages/shops/[shopId]/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/edit/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
  src/pages/shops/[shopId]/notices/register/index.tsx
  src/pages/shops/edit/[shopId].tsx
  src/routes.ts
Labels: 사장님, 기능 추가

#210 내프로필: 내 프로필 페이지 신청 내역
  src/apis/application/index.ts
  src/apis/application/schema.ts
  src/components/my/ApplicationList.tsx
  src/components/my/EmptyApplicationCard.tsx
  src/components/notices/CustomNotice.tsx
  src/components/notices/NoticeListPagination.tsx
  src/components/ui/pagination.tsx
  src/components/ui/table.tsx
  src/pages/my/index.tsx
  src/queries/application.ts
  src/routes.ts
Labels: 기능 추가

#212 공통: /notices 페이지 외 다른 페이지에서 검색 시 검색 안되는 현상 수정 #211
  src/components/notices/NoticeLists.tsx
Labels: 버그 수정

#214 공통: 전체 공고 페이지네이션 페이지 변경 시 화면 최상단으로 이동하는 현상 수정
  src/components/notices/NoticeListPagination.tsx
Labels: 버그 수정

#215 알바님 - 공고 상세 페이지(로그인 상태): 반응형 디자인 구현 + 로딩중 디자인 추가
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
Labels: 알바님, 기능 추가, 디자인

#217 알바님 - 공고 상세 페이지(로그인 상태): 이미 신청한 공고에서 신청 취소되면서 '취소하기' 버튼이 '신청하기' 버튼으로 바뀌는 기능 구현 + 신청 취소 모달창 + 신청 시 프로필 없을 때 나오는 모달창 구현
  src/components/noticeApply/CancelDialog.tsx
  src/components/noticeApply/ProfileRegistDialog.tsx
  src/components/noticeDetail/ApplicationList.tsx
  src/components/noticeDetail/Buttons.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 알바님, 기능 추가, 버그 수정, 디자인

#219 fix: dev와 충돌해결
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
Labels: 버그 수정

#226 fix: 지원 리스트 쿼리 캐시 키 수정
  src/components/my/ApplicationList.tsx
  src/queries/application.ts
Labels: 버그 수정

#229 사장님 - ( 공고 상세 페이지 ): 공고 편집 시 input 내에 공고 등록시의 값을 기본값으로 설정하는 기능 구현
  src/components/shop/ShopDataCard.tsx
  src/hooks/useNoticeEditForm.ts
  src/pages/shops/[shopId]/notices/[noticeId]/edit/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 기능 추가, 디자인

#231 내 프로필: 유저 프로필 수정 폼 구현
  src/components/my/MyEditForm.tsx
  src/components/my/ProfileCard.tsx
  src/hooks/useMyEditForm.ts
  src/pages/my/edit/index.tsx
  src/routes.ts
Labels: 기능 추가

#232 공통: 공고리스트 페이지 필터 버그 수정 및 기능 추가
  src/components/notices/AddressSelector.tsx
  src/components/notices/NoticeListFilter.tsx
  src/components/notices/NoticeLists.tsx
  src/hooks/useDialog.ts
  src/pages/notices/index.tsx
  src/pages/notices/search/index.tsx
  src/providers/ErrorDialogProvider.tsx
  src/styles/globals.css
Labels: 기능 추가, 버그 수정

#234 공통: 에러 모달 디자인 수정 #233
  src/components/common/ErrorDialog.tsx
Labels: 공통 디자인

#242 공통: 공고리스트 페이지 필터 디자인 수정
  src/components/notices/NoticeListFilter.tsx
  src/components/notices/NoticeLists.tsx
  src/components/shop/ShopDataForm.tsx
Labels: 공통 디자인

#244 공고상세페이지(사장님) 반응형 디자인 구현, 시간 표기 에러 해결
  src/components/noticeDetail/ApplicationPagination.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 기능 추가, 디자인

#247 내 프로필: 지원 목록 안 나오는 버그 수정
  src/apis/schema.ts
Labels: 버그 수정

#248 공통 - 마감 / 종료 공고 및 조건에 맞지 않는 공고 표시 변경
  public/icons/grayclock.svg
  public/icons/graypoint.svg
  src/components/notices/CustomNotice.tsx
  src/components/notices/NoticeListCard.tsx
  src/components/notices/NoticeLists.tsx
  src/components/shop/AbleShopsNoticeItem.tsx
  src/components/shop/ShopsNoticesList.tsx
  src/components/shop/ShopsNoticesListItems.tsx
  src/components/shop/UnableShopsNoticeItem.tsx
  tailwind.config.ts
Labels: 공통기능

#249 공고상세페이지(로그인 상태)에서 만료된 공고에 적용할 스타일 구현
  src/components/noticeDetail/Buttons.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 알바님, 기능 추가, 디자인

#251 사장님: /shops/[shopId]/notices/[noticeId] -> /notices/[noticeId] 경로 변경
  src/components/noticeDetail/ApplicationPagination.tsx
  src/components/noticeDetail/NoticeApplyItem.tsx
  src/components/noticeDetail/Pagination.tsx
  src/components/notices/CustomNotice.tsx
  src/components/notices/NoticeListFilter.tsx
  src/components/shop/ShopsNoticesList.tsx
  src/components/shop/ShopsNoticesListItems.tsx
  src/components/shop/UnableShopsNoticeItem.tsx
  src/pages/notices/[noticeId]/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/routes.ts
Labels: 버그 수정, 디자인

#257 내 프로필: 내 프로필 정보 수정 폼에서 주소가 기본값으로 나오는 버그 수정
  src/components/my/MyEditForm.tsx
Labels: 버그 수정

#264 feat: gnb 반응형 추가
  src/components/common/EmployeeHeader.tsx
  tailwind.config.ts
Labels: 공통 디자인

#266 공고상세페이지(로그인 상태) 모바일 디자인 수정
  src/components/shop/AbleShopsNoticeItem.tsx
  src/components/shop/UnableShopsNoticeItem.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
Labels: 알바님, 디자인

#274 공고상세페이지(사장님 ver, 알바님 ver), 편집하기페이지 리팩토링: 컴포넌트 분리, 타입 설정
  src/components/noticeApply/NoticeDetail.tsx
  src/components/noticeApply/RecentNoticeList.tsx
  src/components/noticeDetail/ApplicationList.tsx
  src/components/noticeDetail/ApplicationListComponents.tsx
  src/components/noticeDetail/ApplicationPagination.tsx
  src/components/noticeDetail/NoticeDetail.tsx
  src/components/noticeDetail/Pagination.tsx
  src/components/noticeEdit/RenderFormFields.tsx
  src/hooks/useNoticeEditForm.ts
  src/pages/shops/[shopId]/notices/[noticeId]/apply/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/edit/index.tsx
  src/pages/shops/[shopId]/notices/[noticeId]/index.tsx
Labels: 사장님, 알바님, 환경

#277 fix: 조건에 맞지 않는 공고 미표시 현상 수정
  src/components/notices/CustomNotice.tsx
  src/pages/test.tsx
Labels: 알바님, 버그 수정

#283 공고상세페이지(사장님): 신청자 목록 디자인 재수정
  src/components/noticeDetail/ApplicationList.tsx
Labels: 사장님, 디자인
